ci: binaries-linux-x64: try other static build options

diff --git a/.github/workflows/binaries-linux-x64.yml b/.github/workflows/binaries-linux-x64.yml
--- a/.github/workflows/binaries-linux-x64.yml
+++ b/.github/workflows/binaries-linux-x64.yml
@@ -176,13 +176,13 @@ jobs:
 
     - name: Build with stack
       run: |
-        stack --allow-different-user build --ghc-options='-optl-static -optl-pthread' hledger      # || (echo "ERROR: building hledger failed"; false)
-        stack --allow-different-user build --ghc-options='-optl-static -optl-pthread' hledger-ui   # || (echo "ERROR: building hledger-ui failed"; false)
-        stack --allow-different-user build --ghc-options='-optl-static -optl-pthread' hledger-web  # || (echo "ERROR: building hledger-web failed"; false)
+        stack --allow-different-user build --ghc-options='-optl-static -fPIC' hledger      # || (echo "ERROR: building hledger failed"; false)
+        stack --allow-different-user build --ghc-options='-optl-static -fPIC' hledger-ui   # || (echo "ERROR: building hledger-ui failed"; false)
+        stack --allow-different-user build --ghc-options='-optl-static -fPIC' hledger-web  # || (echo "ERROR: building hledger-web failed"; false)
 
     - name: Run built-in unit tests
       run: |
-        stack exec --ghc-options='-optl-static -optl-pthread' -- hledger test
+        stack exec -- hledger test
 
     - name: Gather binaries
       run: |
