;ci: linux: expect linux builds to be warning free, like the rest

diff --git a/.github/workflows/binaries-linux-x64.yml b/.github/workflows/binaries-linux-x64.yml
--- a/.github/workflows/binaries-linux-x64.yml
+++ b/.github/workflows/binaries-linux-x64.yml
@@ -61,9 +61,9 @@ jobs:
 
     - name: Build with cabal
       run: |
-        cabal build --enable-executable-static hledger || (echo "ERROR: building hledger failed"; false)
-        cabal build --enable-executable-static hledger-ui || (echo "ERROR: building hledger-ui failed"; false)
-        cabal build --enable-executable-static hledger-web || (echo "ERROR: building hledger-web failed"; false)
+        cabal build --enable-executable-static --ghc-options=-Werror hledger || (echo "ERROR: building hledger failed"; false)
+        cabal build --enable-executable-static --ghc-options=-Werror hledger-ui || (echo "ERROR: building hledger-ui failed"; false)
+        cabal build --enable-executable-static --ghc-options=-Werror hledger-web || (echo "ERROR: building hledger-web failed"; false)
 
     - name: Gather binaries
       run: |
