;ci: linux, windows: add unit testing to these

diff --git a/.github/workflows/binaries-linux-x64.yml b/.github/workflows/binaries-linux-x64.yml
--- a/.github/workflows/binaries-linux-x64.yml
+++ b/.github/workflows/binaries-linux-x64.yml
@@ -1,5 +1,5 @@
 # Runs on any push to binaries-linux-x64 or binaries.
-# ACTION: Builds and saves linux x64 static binaries with cabal and the ghc version below and Alpine linux,
+# ACTION: Builds, unit-tests and saves linux x64 static binaries with cabal and the ghc version below and Alpine linux,
 # which provides the statically-linkable musl.
 
 name: binaries-linux-x64
@@ -61,9 +61,9 @@ jobs:
 
     - name: Build with cabal
       run: |
-        cabal build --enable-executable-static --ghc-options=-Werror hledger || (echo "ERROR: building hledger failed"; false)
-        cabal build --enable-executable-static --ghc-options=-Werror hledger-ui || (echo "ERROR: building hledger-ui failed"; false)
-        cabal build --enable-executable-static --ghc-options=-Werror hledger-web || (echo "ERROR: building hledger-web failed"; false)
+        cabal build --test --enable-executable-static --ghc-options=-Werror hledger || (echo "ERROR: building hledger failed"; false)
+        cabal build --test --enable-executable-static --ghc-options=-Werror hledger-ui || (echo "ERROR: building hledger-ui failed"; false)
+        cabal build --test --enable-executable-static --ghc-options=-Werror hledger-web || (echo "ERROR: building hledger-web failed"; false)
 
     - name: Gather binaries
       run: |
