;ci: cleanups

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,33 +1,21 @@
 # The main hledger continuous integration test workflow.
-# Passing this is required for merging/pushing to master, per
-# https://github.com/simonmichael/hledger/settings/branch_protection_rules/17386787
+# Builds all packages expecting no warnings, runs lots of tests,
+# and on success, saves the binaries as an artifact.
+# Code must pass this successfully before it can be merged or pushed to master
+# (https://github.com/simonmichael/hledger/settings/branch_protection_rules/17386787).
 
 name: ci
-
-# When and where does this workflow run ?
 on:
   # When manually triggered in github ui, it runs in master.
   workflow_dispatch:
-
-  # On this schedule, it runs in master.
-  # schedule:
-  # - cron: "0 07 * * 0"  # sunday midnight pacific
-  # Avoid, because these run in all forks also.
-  # Possible workaround; does it prevent wasteful startups ?
-  # https://github.com/orgs/community/discussions/26409#discussioncomment-3251818
-  # jobs:
-  #   job_id:
-  #     if: github.event.pull_request.head.repo.full_name == github.repository
-
-  # When there's a push to the ci branch, it runs there.
-  # After passing there it can be merged/pushed to master.
+  # When there's a push to the ci branch, it runs in that branch.
+  # After it passes, those commits can be merged/pushed to master.
   # (Don't use these branches for pull requests, or it will run twice,
   # https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/2)
   push:
     branches: [ ci ]
-
-  # When there's a pull request against master, it runs in the PR branch.
-  # After passing there it can be merged/pushed to master.
+  # When there's a pull request against master, it runs in the pull request's branch.
+  # After it passes, that branch can be merged/pushed to master.
   pull_request:
     branches: [ master ]
     # Uncomment to run it only for changes to these paths: (but that could prevent merging)
@@ -53,31 +41,14 @@ on:
     #   - '!**.5'
     #   - '!**.info'
     #   - '!**.txt'
-
-# What does it do ?
 jobs:
-
-  # Build all expecting no warnings and run unit/doc/functional/haddock/bench tests,
-  # with the platform(s) and GHC version(s) enabled below.
-  # On success, upload the binaries as a downloadable artifact.
-  ci:
+  citest:
     runs-on: ubuntu-latest
-
-    # strategy:
-    #   fail-fast: false
-    #   matrix:
-    #     # keep synced with branch protection rules, see link above
-    #     plan:
-    #     # the oldest supported ghc, to check backward compatibility
-    #     # - { ghc: "810", stack: "stack --stack-yaml=stack8.10.yaml" }
-    #     - { ghc: "944", stack: "stack --stack-yaml=stack9.4.yaml" }
-
     env:
       ghc:   944
       stack: stack --stack-yaml=stack9.4.yaml
       # declare this to prevent "Context access might be invalid" warnings below
-      CONTINUE:
-
+      do-all:
     steps:
 
     - name: Check out
@@ -86,7 +57,7 @@ jobs:
       with: 
         fetch-depth: 0
 
-    - name: Print debug output
+    - name: Print some context for troubleshooting
       env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
@@ -138,14 +109,14 @@ jobs:
       run: |
         echo "git log -1 --pretty='%s' ${GITHUB_HEAD_REF:+origin/$GITHUB_HEAD_REF} >> $$.gitlog"
         (git log -1 --pretty='%s' ${GITHUB_HEAD_REF:+origin/$GITHUB_HEAD_REF} >> $$.gitlog \
-          && (grep -qE '^ *;' $$.gitlog || echo "CONTINUE=true" >> $GITHUB_ENV)) \
-          || ( echo "could not identify commit range, continuing CI steps"; echo "CONTINUE=true" >> $GITHUB_ENV )
+          && (grep -qE '^ *;' $$.gitlog || echo "do-all=true" >> $GITHUB_ENV)) \
+          || ( echo "could not identify commit range, continuing CI steps"; echo "do-all=true" >> $GITHUB_ENV )
 
     - name: Check embedded files
       run: |
         sudo apt install -y ripgrep
         tools/checkembeddedfiles
-      if: env.CONTINUE
+      if: env.do-all
 
     # things to be cached/restored:
 
@@ -160,7 +131,7 @@ jobs:
         key: ${{ runner.os }}-stack-global-$ghc-${{ hashFiles('**.yaml') }}
         restore-keys: |
              ${{ runner.os }}-stack-global-$ghc
-      if: env.CONTINUE
+      if: env.do-all
 
     - name: Uncache stack-installed programs in ~/.local/bin
       id:   stack-programs
@@ -170,7 +141,7 @@ jobs:
         key: ${{ runner.os }}-stack-programs-$ghc-${{ hashFiles('**.yaml') }}
         restore-keys: |
              ${{ runner.os }}-stack-programs-$ghc
-      if: env.CONTINUE
+      if: env.do-all
 
     - name: Uncache .stack-work
       uses: actions/cache@v4
@@ -179,7 +150,7 @@ jobs:
         key: ${{ runner.os }}-stack-work-$ghc-${{ hashFiles('**.yaml') }}
         restore-keys: |
              ${{ runner.os }}-stack-work-$ghc
-      if: env.CONTINUE
+      if: env.do-all
 
     - name: Uncache hledger-lib/.stack-work
       uses: actions/cache@v4
@@ -188,7 +159,7 @@ jobs:
         key: ${{ runner.os }}-hledger-lib-stack-work-$ghc-${{ hashFiles('hledger-lib/package.yaml') }}
         restore-keys: |
              ${{ runner.os }}-hledger-lib-stack-work-$ghc
-      if: env.CONTINUE
+      if: env.do-all
 
     - name: Uncache hledger/.stack-work
       uses: actions/cache@v4
@@ -197,7 +168,7 @@ jobs:
         key: ${{ runner.os }}-hledger-stack-work-$ghc-${{ hashFiles('hledger/package.yaml') }}
         restore-keys: |
              ${{ runner.os }}-hledger-stack-work-$ghc
-      if: env.CONTINUE
+      if: env.do-all
 
     - name: Uncache hledger-ui/.stack-work
       uses: actions/cache@v4
@@ -206,7 +177,7 @@ jobs:
         key: ${{ runner.os }}-hledger-ui-stack-work-$ghc-${{ hashFiles('hledger-ui/package.yaml') }}
         restore-keys: |
              ${{ runner.os }}-hledger-ui-stack-work-$ghc
-      if: env.CONTINUE
+      if: env.do-all
 
     - name: Uncache hledger-web/.stack-work
       uses: actions/cache@v4
@@ -215,7 +186,7 @@ jobs:
         key: ${{ runner.os }}-hledger-web-stack-work-$ghc-${{ hashFiles('hledger-web/package.yaml') }}
         restore-keys: |
              ${{ runner.os }}-hledger-web-stack-work-$ghc
-      if: env.CONTINUE
+      if: env.do-all
 
     # actions:
 
@@ -226,21 +197,20 @@ jobs:
         # curl -sL https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack
         if [[ ! -x ~/.local/bin/stack ]]; then curl -sL https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack; fi
         stack --version
-      if: env.CONTINUE
+      if: env.do-all
 
     - name: Install GHC
       run: |
         $stack setup --install-ghc
-      if: env.CONTINUE
+      if: env.do-all
 
     - name: Install haskell deps
       run: |
         $stack build --test --bench --only-dependencies --dry-run
         $stack build --test --bench --only-dependencies
-      if: env.CONTINUE
+      if: env.do-all
 
     # Packages are built one at a time to fail faster on error.
-    # Note: doctests won't run if using GHC 9.0, see hledger-lib/package.yaml
     # Takes ~2m on a 2023 github worker.
     - name: Build all hledger modules fast, warning free, run unit/doc/bench tests
       run: |
@@ -249,14 +219,14 @@ jobs:
         $stack install --fast --ghc-options=-Werror  --test --bench hledger-ui
         $stack install --fast --ghc-options=-Werror  --test --bench hledger-web
         #  --ghc-options=-split-sections --no-terminal
-      if: env.CONTINUE
+      if: env.do-all
 
     - name: Install shelltestrunner
       run: |
         export PATH=~/.local/bin:$PATH
         if [[ ! -x ~/.local/bin/shelltest ]]; then $stack install shelltestrunner-1.10; fi
         shelltest --version
-      if: env.CONTINUE
+      if: env.do-all
 
     # Takes ~30s on a 2023 github worker.
     - name: Test functional tests (excluding addons)
@@ -264,10 +234,10 @@ jobs:
         export PATH=~/.local/bin:$PATH
         COLUMNS=80 $stack exec -- shelltest --execdir -j16 hledger/test -x /_ -x /addons -x ledger-compat/ledger-baseline -x ledger-compat/ledger-regress -x ledger-compat/ledger-collected
         # XXX run the bin/ func tests corresponding to the GHC version enabled above, only
-      if: env.CONTINUE
+      if: env.do-all
 
     # Takes 1m+ on a 2023 github worker.
-    # Moved to (one of) the binaries-* workflows instead;
+    # Moved to binaries-mac-arm64 workflow instead;
     # haddock breakage might not be found until release time but it's easy to fix.
     # - name: Test haddock generation
     #   env:
@@ -277,7 +247,7 @@ jobs:
     #     time $stack build --fast --haddock --no-haddock-deps --no-haddock-hyperlink-source --haddock-arguments="--no-print-missing-docs" || echo "HADDOCK FAILED, IGNORING"
     #     # --no-haddock-hyperlink-source is 25% faster
     #     # --no-print-missing-docs is 600% quieter
-    #   if: env.CONTINUE
+    #   if: env.do-all
 
     - name: Gather binaries
       id: exes
@@ -291,10 +261,7 @@ jobs:
         strip hledger-ui
         strip hledger-web
         tar cvf hledger-linux-x64.tar hledger hledger-ui hledger-web
-      if: env.CONTINUE
-
-      # how to set a context variable, and an attempt to make a nice artifact version suffix:
-      # echo "::set-output name=version::$(git branch --show-current | sed 's/-.*//')-$(git rev-parse --short HEAD)"
+      if: env.do-all
 
     # upload-artifact loses execute permissions, so we tar the binaries to preserve them.
     # github UI always zips artifacts when they are downloaded, so we don't bother compressing the tar.
@@ -304,10 +271,14 @@ jobs:
       with:
         name: hledger-linux-x64
         path: tmp/hledger-linux-x64.tar
-      if: env.CONTINUE
+      if: env.do-all
 
 
 
+    # snippets
+
+    # how to set a context variable, and an attempt to make a nice artifact version suffix:
+    #   echo "::set-output name=version::$(git branch --show-current | sed 's/-.*//')-$(git rev-parse --short HEAD)"
 
     # - name: show stuff
     #   run: |
